name: astronomy
description: "A Flutter app built with Clean Architecture and TDD to exploit the Astronomy Picture of the Day API. This app allows users to select a date and view photos of the galaxy captured by NASA on that specific date."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  mockito: ^5.4.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true